### ISSUE TITLE
Changing parameters of a texture when someone else is using the tool causes issues [Multiplayer]

### ISSUE THREAD

**Issue by VCSoldier** [CFC-Servers/material-editor-tool#5]
wood/woodfloor007a_c17 < texture being used

https://github.com/CFC-Servers/material-editor-tool/assets/50423227/466aec60-a1e4-46f5-ae0b-403940915a39

unsure as to what is causing it, possibly the new system used for caching textures not enjoying its time on multiplayer

**Comment by VCSoldier** [comment]
https://github.com/CFC-Servers/material-editor-tool/assets/50423227/9bb581b9-887a-47b4-a8aa-ffe0d4b0f3fa

seems like whatever your using in multiplayer to update the texture isnt refreshing the texture properly once applied

**Comment by wrefgtzweve** [comment]
I'll look into this. I was able to replicate the issue, thanks for reporting the issue.

**Comment by wrefgtzweve** [comment]
Should be fixed in the latest update https://steamcommunity.com/sharedfiles/filedetails/changelog/3118788923
